### ISSUE TITLE
Cant activate two sipra entities

### ISSUE THREAD

**Issue by jaimecasero** [Mobicents/jain-slee.sip#27]
after activating the second one we get:
L
08:38:20,964 ERROR [SipResourceAdaptor](http-0.0.0.0-8080-3) error in initializing resource adaptor
java.util.TooManyListenersException: Stack already has a listener. Only one listener per stack allowed
        at gov.nist.javax.sip.SipProviderImpl.addSipListener(SipProviderImpl.java:221)
        at org.mobicents.slee.resource.sip11.SipResourceAdaptor.raActive(SipResourceAdaptor.java:1271)
        at org.mobicents.slee.resource.ResourceAdaptorObjectImpl.raActive(ResourceAdaptorObjectImpl.java:255)
        at org.mobicents.slee.resource.ResourceAdaptorEntityImpl.activate(ResourceAdaptorEntityImpl.java:374)
        at org.mobicents.slee.container.management.ResourceManagementImpl.activateResourceAdaptorEntity(ResourceManagementImpl.java:275)
        at org.mobicents.slee.container.management.jmx.ResourceManagementMBeanImpl.activateResourceAdaptorEntity(ResourceManagementMBeanImpl.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
        at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)

This maybe an actual slee isssue, since classloading may be affecting the initialization

**Comment by yarel79** [comment]
PR with the fix created: https://github.com/RestComm/jain-slee.sip/pull/28

**Comment by yarel79** [comment]
I guess this issue can be closed, since fix is merged.

**Comment by SergeyLee** [comment]
@yarel79 Sure. Thanks!
